export const portfolioContent = {
  nav: {
    name: "Muhammad Imran",
    role: "Full Stack Web Developer",
    avatar: "/imran1.png",
    availability: "Available",
    links: [
      { label: "Home", to: "/", target: "home" },
      { label: "About", to: "/about", target: "about" },
      { label: "Skills", to: "/", target: "skills" },
      { label: "Projects", to: "/projects", target: "projects" },
    ],
    contactLabel: "Contact",
  },
  hero: {
    name: "Muhammad Imran",
    eyebrow: "Muhammad Imran",
    headlineLeft: "WEB",
    headlineRight: "DEVELOPER",
    taglineRight: "I build full-stack web products with clean code and polished user experience.",
    bubble: "Hi",
    previewImage: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=500&q=80",
    accentDots: [
      { className: "left-[8%] top-[38%] h-3 w-3" },
      { className: "right-[13%] top-[28%] h-2.5 w-2.5" },
      { className: "left-[27%] bottom-[18%] h-2 w-2" },
    ],
  },
  stickyVisual: {
    statusText: "Available for work",
    avatar: "/imran1.png",
    backTitle: "Web services",
    backText: "Full-stack apps, business websites, APIs, and AI workflows.",
    backItems: ["MERN Stack", "Ruby on Rails", "AI Integration"],
    images: [
      {
        label: "Portrait",
        src: "/imran1.png",
      },
      {
        label: "Portrait",
        src: "/imran1.png",
      },
      {
        label: "Portrait",
        src: "/imran1.png",
      },
    ],
  },
  services: {
    title: "WHAT I CAN DO FOR YOU",
    description: "Simple, practical web services that help your business look better, work faster, and serve customers more clearly.",
    items: [
      {
        title: "Custom Website Development",
        points: ["Modern business websites", "Responsive layouts", "Clear user journeys", "Built around your goals"],
      },
      {
        title: "Full-Stack Web Applications",
        points: ["Complete web solutions", "User-friendly interfaces", "Secure functionality", "Ready for real use"],
      },
      {
        title: "AI & Chatbot Solutions",
        points: ["Smart customer support", "Helpful AI features", "Faster responses", "Better user experience"],
      },
      {
        title: "Business Automation",
        points: ["Reduce repetitive work", "Streamline daily tasks", "Save team time", "Improve workflow clarity"],
      },
      {
        title: "API & System Integration",
        points: ["Connect existing tools", "Share data smoothly", "Improve business flow", "Reduce manual updates"],
      },
      {
        title: "E-commerce Solutions",
        points: ["Reliable online stores", "Smooth customer checkout", "Product management", "Sales-focused experience"],
      },
      {
        title: "Performance & Maintenance",
        points: ["Improve page speed", "Keep apps reliable", "Fix issues quickly", "Support ongoing growth"],
      },
    ],
  },
  about: {
    title: "ABOUT ME",
    intro: "I am a full-stack web developer building polished apps, business websites, and AI-powered workflows.",
    stats: [
      { value: 1, suffix: "+", label: "Years Experience" },
      { value: 20, suffix: "+", label: "Projects Built" },
      { value: 10, suffix: "+", label: "Technologies" },
    ],
    contact: {
      phoneLabel: "Call Today :",
      phone: "03087153947",
      emailLabel: "Email :",
      email: "imranwebcreator@gmail.com",
    },
    storyCta: "MY STORY",
    storyTarget: "/about",
  },
  socials: [
    { label: "GitHub", href: "https://github.com/malikimranawan" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/malik-imran-598b96241/" },
    { label: "Instagram", href: "#" },
    { label: "Email", href: "mailto:imranwebcreator@gmail.com" },
  ],
  projects: {
    title: "Featured Projects",
    description: "A showcase of my recent engineering challenges, from full-stack architectures to deeply integrated AI solutions.",
    cta: "View All Projects",
    items: [
      {
        category: "AI Powered",
        title: "YouTube Sentiment Bot",
        description: "An AI-powered MERN stack application that analyzes YouTube video comments to determine audience sentiment and generate clear insights.",
        tech: "LangChain.js, React, Node.js, Express, MongoDB",
        image: "/youtube-sentiment-bot.png",
        github: "https://github.com/malikimran-khan/youtube-sentiment-bot",
      },
      {
        category: "AI Powered",
        title: "Auto LinkedIn Poster",
        description: "An AI-driven content automation tool that generates professional LinkedIn posts and supports publishing workflows.",
        tech: "LangChain.js, React, Node.js, Express, MongoDB, OpenAI API",
        image: "/auto-linkdin-poster.png",
        github: "https://github.com/malikimran-khan/smart-content-generator-post-on-linkdin",
      },
      {
        category: "AI Powered",
        title: "AI Emporium",
        description: "A full-featured AI-powered eCommerce platform with role-based dashboards, product management, analytics, and an AI chatbot.",
        tech: "LangChain.js, React, Node.js, Express, MongoDB, OpenAI API",
        image: "/ai-emporium.png",
        github: "https://github.com/malikimran-khan/ai-emporium",
      },
    ],
    libraryItems: [
      {
        category: "Frontend",
        title: "Saleem Enterprises",
        description: "Smart agriculture platform using AI and IoT to optimize greenhouse climate, irrigation, and crop productivity with real-time monitoring.",
        tech: "React, Tailwind, Three.js",
        image: "/saleem.webp",
      },
      {
        category: "Frontend",
        title: "Libra Printing",
        description: "A professional website for printing services showcasing quality printing solutions, modern design, and industrial capabilities.",
        tech: "React, Tailwind",
        image: "/demo-image.webp",
      },
      {
        category: "Frontend",
        title: "Ab Exports",
        description: "A business website for textile exports highlighting products, services, and global trade operations with a modern UI.",
        tech: "React, Tailwind",
        image: "/ab.webp",
      },
      {
        category: "Frontend",
        title: "Broshtech",
        description: "A tech-focused business website showcasing innovative solutions with responsive design, modern UI, and smooth animations.",
        tech: "React, Tailwind",
        image: "/broshtech.png",
      },
      {
        category: "Frontend",
        title: "Para Mount Solutions",
        description: "A global sourcing platform connecting buyers with manufacturers through transparent and efficient trade operations.",
        tech: "React, Tailwind",
        image: "/para.png",
      },
      {
        category: "Frontend",
        title: "Iqbal Pipes",
        description: "An industrial website showcasing pipe products, company services, and engineering expertise with a durable visual style.",
        tech: "React, Tailwind",
        image: "/iqbal.png",
      },
      {
        category: "Frontend",
        title: "Money Move",
        description: "A construction and interior design website presenting premium projects with luxury-focused visuals and polished layout.",
        tech: "React, Tailwind",
        image: "/money-move.png",
      },
      {
        category: "Frontend",
        title: "Naseem Fabrics",
        description: "A textile and fashion website showcasing fabric collections with a clean, modern, and responsive design.",
        tech: "React, Tailwind",
        image: "/naseem.png",
      },
      {
        category: "Full Stack",
        title: "Ai Verse",
        description: "A digital agency and software house platform for web development, games, 3D modeling, digital marketing, and creative software services.",
        tech: "React, Framer Motion, Tailwind, Three.js, AI Integration",
        image: "/ai-verse.png",
      },
      {
        category: "Full Stack",
        title: "Waaris Fabric Store",
        description: "An e-commerce platform for premium fabrics and custom stitching with product browsing, outfit customization, and smooth ordering.",
        tech: "React, Shopify, Tailwind",
        image: "/waaris.webp",
      },
      {
        category: "Full Stack",
        title: "Netrics",
        description: "An AI-powered LinkedIn automation platform that generates, edits, schedules, and publishes professional posts.",
        tech: "LangChain.js, React, Node.js, MongoDB, OpenAI API",
        image: "/netrics.png",
      },
      {
        category: "Full Stack",
        title: "Care Connect",
        description: "A volunteer management platform connecting volunteers with organizations through opportunity discovery, dashboards, and real-time chat.",
        tech: "React, Node.js, MongoDB, Socket.IO",
        image: "/careconnect.png",
      },
      {
        category: "Full Stack",
        title: "Smart Health Connect System",
        description: "A healthcare platform for patients and doctors with appointment booking, real-time chat, dashboards, admin analytics, and AI assistance.",
        tech: "React, Node.js, Express, MongoDB, Socket.IO, JWT, OpenAI API",
        image: "/health-system.png",
      },
      {
        category: "Full Stack",
        title: "Smart Office Attendance & Management System",
        description: "A workforce management system with role-based access, employee verification, attendance tracking, and salary calculations.",
        tech: "React, Node.js, MongoDB, PWA",
        image: "/attendence-system.png",
      },
      {
        category: "Full Stack",
        title: "Skill Swap",
        description: "A PWA-based employee attendance and management system with verification, admin controls, and salary calculations.",
        tech: "React, Node.js, MongoDB, PWA",
        image: "/skill-swap.png",
      },
      {
        category: "AI Powered",
        title: "YouTube Sentiment Bot",
        description: "An AI-powered MERN application that analyzes YouTube comments and generates clear positive, negative, or neutral audience insights.",
        tech: "LangChain.js, React, Node.js, Express, MongoDB",
        image: "/youtube-sentiment-bot.png",
        github: "https://github.com/malikimran-khan/youtube-sentiment-bot",
      },
      {
        category: "AI Powered",
        title: "Auto LinkedIn Poster",
        description: "An AI-driven automation tool that creates professional LinkedIn posts and supports publishing workflows.",
        tech: "LangChain.js, React, Node.js, Express, MongoDB, OpenAI API",
        image: "/auto-linkdin-poster.png",
        github: "https://github.com/malikimran-khan/smart-content-generator-post-on-linkdin",
      },
      {
        category: "AI Powered",
        title: "AI Emporium",
        description: "An AI-powered eCommerce platform with role-based dashboards, product management, analytics, and a product discovery chatbot.",
        tech: "LangChain.js, React, Node.js, Express, MongoDB, OpenAI API",
        image: "/ai-emporium.png",
        github: "https://github.com/malikimran-khan/ai-emporium",
      },
      {
        category: "AI Powered",
        title: "Intelligent Quiz System",
        description: "An AI quiz platform that generates topic-based MCQs, evaluates answers in real time, and shows explanations and analytics.",
        tech: "React, Node.js, Express, MongoDB, OpenAI API, Chart.js",
        image: "/quiz.png",
        github: "https://github.com/malikimran-khan/Intelligent-quiz-system",
      },
      {
        category: "AI Powered",
        title: "Resume Analyzer",
        description: "An AI resume analysis tool that checks strengths, weaknesses, keyword optimization, formatting, and ATS improvements.",
        tech: "React, Node.js, Express, MongoDB, OpenAI API",
        image: "/resume-analyzer.png",
        link: "https://resume-analyzer-hduo.vercel.app/",
        github: "https://github.com/malikimran-khan/resume-analyzer",
      },
      {
        category: "AI Powered",
        title: "Personal AI Chatbot",
        description: "A customizable chatbot platform for intelligent assistants that answer questions, provide recommendations, and support productivity.",
        tech: "React, Node.js, Express, MongoDB, OpenAI API",
        image: "/personal-chat-bot.png",
        link: "https://personal-ai-chatbot-platform.vercel.app/",
        github: "https://github.com/malikimran-khan/personal-ai-chatbot",
      },
      {
        category: "AI Powered",
        title: "Interview Simulator",
        description: "An AI interview preparation platform that generates role-based questions and gives feedback, scoring, and improvement suggestions.",
        tech: "React, Node.js, Express, MongoDB, OpenAI API",
        image: "/interview-simulator.png",
        link: "https://ai-interview-simulator-7e54.vercel.app/",
        github: "https://github.com/malikimran-khan/ai-interview-simulator",
      },
      {
        category: "AI Powered",
        title: "AI Career Advisor",
        description: "An AI career guidance platform that recommends career paths, required skills, and learning roadmaps based on user interests.",
        tech: "React, Node.js, Express, MongoDB, OpenAI API",
        image: "/ai-career.png",
      },
    ],
  },
  testimonials: {
    title: "Work Highlights",
    description: "Focused delivery across product engineering, integrations, and responsive interfaces.",
    cards: [
      {
        quote: "Built product-based Rails features with payment and API integrations.",
        name: "Techbolic Solutions",
        role: "Associate Software Engineer",
        avatar: "/broshtech.png",
      },
      {
        quote: "Delivered scalable MERN apps, AI tools, and responsive product interfaces.",
        name: "BroshTech",
        role: "MERN Stack Developer",
        avatar: "/broshtech.png",
      },
      {
        quote: "Worked with Secucard, ChargeCloud, OCR, LangChain, and OpenAI.",
        name: "Integration Work",
        role: "Rails + AI",
        avatar: "/imran.png",
      },
      {
        quote: "Focused on performance, clean UX, and maintainable product structure.",
        name: "Delivery Style",
        role: "Clean & Scalable",
        avatar: "/imran.png",
      },
    ],
    highlights: [
      { intro: "Projects built across web, AI, and business workflows", value: 20, suffix: "+", label: "Projects" },
      { intro: "Hands-on with modern product technologies", value: 10, suffix: "+", label: "Technologies" },
    ],
  },
  faq: {
    title: "FREQUENTLY ASKED QUESTIONS",
    description: "Here are answers to some of the most common questions I receive as a freelance designer. If you don't see your question here, feel free to reach out - I'm happy to help!",
    items: [
      { question: "What services do you offer?", answer: "I offer web design, UI/UX design, branding support, and full-stack implementation for polished digital products." },
      { question: "How does the design process work?", answer: "We start with goals, define the structure, create the design, refine it with feedback, then prepare it for launch." },
      { question: "How long does a project usually take?", answer: "Most projects take two to six weeks depending on scope, content, and revision rounds." },
      { question: "What do I need to provide before starting a project?", answer: "A short brief, brand assets if available, content direction, and examples of the style you like are enough to begin." },
      { question: "Do you offer revisions?", answer: "Yes. Revisions are included so the final result feels clear, polished, and aligned with the project goals." },
      { question: "How do I get started?", answer: "Send a quick message with your project idea, timeline, and service needs. I will reply with the next steps." },
    ],
  },
  blogs: {
    title: "Featured AI Powered",
    description: "AI-powered MERN applications, automation tools, chatbots, and intelligent platforms built around practical use cases.",
    filters: ["Frontend", "Full Stack", "AI Powered"],
    cta: "Explore All Projects",
    featured: [
      {
        category: "Featured AI Powered",
        date: "LangChain.js, React, Node.js, Express, MongoDB",
        title: "YouTube Sentiment Bot",
        excerpt: "An AI-powered MERN stack application that analyzes YouTube video comments to determine audience sentiment and generate clear positive, negative, or neutral insights.",
        image: "/youtube-sentiment-bot.png",
        github: "https://github.com/malikimran-khan/youtube-sentiment-bot",
      },
      {
        category: "AI Powered",
        date: "LangChain.js, React, Node.js, Express, MongoDB, OpenAI API, LinkedIn Automation, Tailwind CSS",
        title: "Auto LinkedIn Poster",
        excerpt: "An AI-driven content automation tool that generates professional LinkedIn posts from user topics and supports LinkedIn publishing workflows.",
        image: "/auto-linkdin-poster.png",
        github: "https://github.com/malikimran-khan/smart-content-generator-post-on-linkdin",
      },
    ],
    latestTitle: "More AI Powered Projects",
    items: [
      {
        category: "AI Powered",
        date: "LangChain.js, React, Node.js, Express, MongoDB, OpenAI API, Chart.js, Tailwind CSS, JWT Authentication, REST APIs",
        title: "AI Emporium",
        excerpt: "A full-featured AI-powered eCommerce platform with Admin, Seller, and Buyer roles, product management, analytics dashboards, and an AI chatbot for product discovery.",
        image: "/ai-emporium.png",
        github: "https://github.com/malikimran-khan/ai-emporium",
      },
      {
        category: "AI Powered",
        date: "React, Node.js, Express, MongoDB, OpenAI API, PWA, Tailwind CSS, JWT Authentication, REST APIs, Chart.js",
        title: "Intelligent Quiz System",
        excerpt: "An AI-powered quiz platform that dynamically generates MCQs by topic and level, evaluates answers in real time, and provides explanations and analytics.",
        image: "/quiz.png",
        github: "https://github.com/malikimran-khan/Intelligent-quiz-system",
      },
      {
        category: "AI Powered",
        date: "React, Node.js, Express, MongoDB, OpenAI API, Tailwind CSS, REST APIs, Cloud File Storage",
        title: "Resume Analyzer",
        excerpt: "An AI-powered resume analysis tool that reviews resumes for strengths, weaknesses, keyword optimization, formatting, and ATS improvement tips.",
        image: "/resume-analyzer.png",
        link: "https://resume-analyzer-hduo.vercel.app/",
        github: "https://github.com/malikimran-khan/resume-analyzer",
      },
      {
        category: "AI Powered",
        date: "React, Node.js, Express, MongoDB, OpenAI API, Tailwind CSS, REST APIs",
        title: "Personal AI Chatbot",
        excerpt: "A customizable AI chatbot platform that lets users create and interact with intelligent assistants for queries, recommendations, and human-like conversations.",
        image: "/personal-chat-bot.png",
        link: "https://personal-ai-chatbot-platform.vercel.app/",
        github: "https://github.com/malikimran-khan/personal-ai-chatbot",
      },
      {
        category: "AI Powered",
        date: "React, Node.js, Express, MongoDB, OpenAI API, Tailwind CSS, REST APIs",
        title: "Interview Simulator",
        excerpt: "An AI-powered interview preparation platform that simulates real interview scenarios, generates role-based questions, and provides feedback on answers.",
        image: "/interview-simulator.png",
        link: "https://ai-interview-simulator-7e54.vercel.app/",
        github: "https://github.com/malikimran-khan/ai-interview-simulator",
      },
      {
        category: "AI Powered",
        date: "React, Node.js, Express, MongoDB, OpenAI API, Tailwind CSS, REST APIs",
        title: "AI Career Advisor",
        excerpt: "An AI-powered career guidance platform that analyzes user skills, education, and interests to recommend career paths, skills, and learning roadmaps.",
        image: "/ai-career.png",
      },
    ],
  },
  contact: {
    title: "LET'S WORK TOGETHER",
    description: "Let's build something impactful together - whether it's your brand, your website, or your next big idea.",
    bubble: "Hi",
    portrait: "/imran1.png",
    fields: {
      name: "Name",
      namePlaceholder: "John Smith",
      email: "Email",
      emailPlaceholder: "johnsmith@gmail.com",
      service: "Service Needed ?",
      servicePlaceholder: "Select...",
      services: ["Ruby on Rails", "MERN Stack", "AI Integration", "Client Website"],
      message: "What Can I Help You...",
      messagePlaceholder: "Hello, I'd like to enquire about...",
      submit: "Submit",
    },
  },
  footer: {
    copyright: "All Rights Reserved by Muhammad Imran.",
    credit: "Created by Muhammad Imran",
  },
};
